### ISSUE TITLE
Potential holes

### ISSUE THREAD

**Issue by hitsthings** [secure-require/secure-require#7]
This is an awesome idea and I'm keen to try it out!

Was looking at the source and thinking about potential holes worth looking at. You've probably thought of them but I figured it couldn't hurt to help:
- fs can be used in conjunction with eval/vm to run code, perhaps including core modules. Is there a way to avoid the fs module being a Game Over?
- do WebAssembly modules open any holes?
- your source already has a note about native modules.
- can any core modules be found by requiring other core modules and navigating prototype chains?
- can the prototype chain of the require function you pass in be navigated to access anything?
- Can I access core modules via the debugger port if the app is run with --inspect and 'net' is permitted?
- child_process obviously exposes everything since you can just run node again.

I'm happy to investigate any that you haven't yet, if you're looking for help.

Cheers!

**Comment by ryzokuken** [comment]
Hi @hitsthings!

Thanks for making this issue. You do infact echo a lot of my concerns and I really appreciate that. I could use all the help in the world auditing this package and finding potential vulnerabilities.

> * fs can be used in conjunction with eval/vm to run code, perhaps including core modules. Is there a way to avoid the fs module being a Game Over?

Interesting! Could you look if it's viable to do something like that practically for this module? I hadn't been paying a lot of heed to this case specifically.

> * do WebAssembly modules open any holes?

They certainly open up a whole Pandora's box of weird cases and issues. For now, I'm focussing on making this work for CJS modules. If that is achieved, I would not believe ESM would prove to be much of a challenge because of the loader patching capabilities offered. WASM next, I guess?

> * your source already has a note about native modules.

Yes, that is certainly something I am planning to investigate more about soon.

> * can any core modules be found by requiring other core modules and navigating prototype chains?

I hope not. I'm plugging all the holes in that direction right now (disallowing setting properties on core modules, etc), but I'm still actively exploring any and every avenue of attack.

> * can the prototype chain of the require function you pass in be navigated to access anything?

I'd say that has been taken care of in the recent few PRs I made, I'm trying to be extra sure, but as with everything else, any holes you can find would be nice.

> * Can I access core modules via the debugger port if the app is run with --inspect and 'net' is permitted?

I'd never considered that possibility tbqh. I'll explore that soon.

> * child_process obviously exposes everything since you can just run node again.

Yes, if you allow a module to spawn processes on your machine, any sense of security just goes out of the window. It's quite literally allowing the module to execute arbitrary code on your machine. Perhaps you'd be inclined to print out a warning when this permission is granted? 😄 

> I'm happy to investigate any that you haven't yet, if you're looking for help.

Thank you so much for the offer. I would appreciate every single piece of help I can get, since I can only do so much.

One workflow that might work is that if you ever find a certain case that fails for the current state of the module, either ping me or file an issue or make a PR with a failing test case. Then I could either help you figure out a fix, or push a fix to your branch. Sounds good?

Thanks for the kind words and help, closing this issue in particular but looking forward to hear from you.

**Comment by hitsthings** [comment]
Awesome, thanks for the detailed response! I'll poke around later today and see if I can prove-ably find any issues.
